package com.hotel.dao.base;

import java.util.List;
import java.util.Map;

import com.hotel.core.MyBatisRepository;
import com.hotel.model.base.DeviceState;
import com.hotel.viewmodel.base.OperationVM;

@MyBatisRepository
public interface DeviceStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int insert(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int insertSelective(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    DeviceState selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int updateByPrimaryKeySelective(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int updateByPrimaryKey(DeviceState record);

    /**
     * 获取操作记录总数，用于分页
     * @param map
     * @return
     */
	int countByMap(Map<String, Object> map);

	/**
	 * 获取操作记录列表，分页显示
	 * @param map
	 * @return
	 */
	List<OperationVM> loadOperationVMList(Map<String, Object> map);
}