package com.hotel.dao;

import com.hotel.core.MyBatisRepository;
import com.hotel.model.DeviceState;

@MyBatisRepository
public interface DeviceStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int insert(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int insertSelective(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    DeviceState selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int updateByPrimaryKeySelective(DeviceState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_state
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int updateByPrimaryKey(DeviceState record);
}