package com.hotel.dao;

import com.hotel.model.Occupancy;

public interface OccupancyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupancy
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupancy
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int insert(Occupancy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupancy
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int insertSelective(Occupancy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupancy
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    Occupancy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupancy
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int updateByPrimaryKeySelective(Occupancy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_occupancy
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int updateByPrimaryKey(Occupancy record);
}