package com.hotel.dao;

import com.hotel.core.MyBatisRepository;
import com.hotel.model.Rcu;

@MyBatisRepository
public interface RcuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rcu
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rcu
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int insert(Rcu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rcu
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int insertSelective(Rcu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rcu
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    Rcu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rcu
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int updateByPrimaryKeySelective(Rcu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rcu
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int updateByPrimaryKey(Rcu record);
}