package com.hotel.dao;

import java.util.List;
import java.util.Map;
import com.hotel.core.MyBatisRepository;
import com.hotel.model.RoomType;
import com.hotel.viewmodel.RoomTypeVM;

@MyBatisRepository
public interface RoomTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_room_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_room_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int insert(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_room_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int insertSelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_room_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    RoomType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_room_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int updateByPrimaryKeySelective(RoomType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_room_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    int updateByPrimaryKey(RoomType record);

    /**
     * 获取房间类型呢记录总数
     * @param map
     * @return
     */
	int countByMap(Map<String, Object> map);

	/**
	 * 获取房间类型列表，分页显示
	 * @param map
	 * @return
	 */
	List<RoomTypeVM> loadRoomTypeList(Map<String, Object> map);
}
