package com.hotel.model.base;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.name
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.idcard
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.mobile
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.mobile_md5
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String mobileMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.reg_time
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Date regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.sex
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer.psd
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String psd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.id
     *
     * @return the value of t_customer.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.id
     *
     * @param id the value for t_customer.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.name
     *
     * @return the value of t_customer.name
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.name
     *
     * @param name the value for t_customer.name
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.idcard
     *
     * @return the value of t_customer.idcard
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.idcard
     *
     * @param idcard the value for t_customer.idcard
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.mobile
     *
     * @return the value of t_customer.mobile
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.mobile
     *
     * @param mobile the value for t_customer.mobile
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.mobile_md5
     *
     * @return the value of t_customer.mobile_md5
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getMobileMd5() {
        return mobileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.mobile_md5
     *
     * @param mobileMd5 the value for t_customer.mobile_md5
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setMobileMd5(String mobileMd5) {
        this.mobileMd5 = mobileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.reg_time
     *
     * @return the value of t_customer.reg_time
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.reg_time
     *
     * @param regTime the value for t_customer.reg_time
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.sex
     *
     * @return the value of t_customer.sex
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.sex
     *
     * @param sex the value for t_customer.sex
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer.psd
     *
     * @return the value of t_customer.psd
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getPsd() {
        return psd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer.psd
     *
     * @param psd the value for t_customer.psd
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setPsd(String psd) {
        this.psd = psd;
    }
}