package com.hotel.model.base;

public class Region {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.parent_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.name
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.level
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.path
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_region.note
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.id
     *
     * @return the value of t_region.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.id
     *
     * @param id the value for t_region.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.parent_id
     *
     * @return the value of t_region.parent_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.parent_id
     *
     * @param parentId the value for t_region.parent_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.name
     *
     * @return the value of t_region.name
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.name
     *
     * @param name the value for t_region.name
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.level
     *
     * @return the value of t_region.level
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.level
     *
     * @param level the value for t_region.level
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.path
     *
     * @return the value of t_region.path
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.path
     *
     * @param path the value for t_region.path
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_region.note
     *
     * @return the value of t_region.note
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_region.note
     *
     * @param note the value for t_region.note
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }
}