package com.hotel.model;

import java.util.Date;

public class DeviceState {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_state.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_state.state_time
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Date stateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_state.occupancy_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String occupancyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_state.rcu_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer rcuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_state.ctl_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer ctlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_state.device_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer deviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_state.value
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_state.id
     *
     * @return the value of t_device_state.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_state.id
     *
     * @param id the value for t_device_state.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_state.state_time
     *
     * @return the value of t_device_state.state_time
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Date getStateTime() {
        return stateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_state.state_time
     *
     * @param stateTime the value for t_device_state.state_time
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setStateTime(Date stateTime) {
        this.stateTime = stateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_state.occupancy_id
     *
     * @return the value of t_device_state.occupancy_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getOccupancyId() {
        return occupancyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_state.occupancy_id
     *
     * @param occupancyId the value for t_device_state.occupancy_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setOccupancyId(String occupancyId) {
        this.occupancyId = occupancyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_state.rcu_id
     *
     * @return the value of t_device_state.rcu_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getRcuId() {
        return rcuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_state.rcu_id
     *
     * @param rcuId the value for t_device_state.rcu_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setRcuId(Integer rcuId) {
        this.rcuId = rcuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_state.ctl_type
     *
     * @return the value of t_device_state.ctl_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getCtlType() {
        return ctlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_state.ctl_type
     *
     * @param ctlType the value for t_device_state.ctl_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setCtlType(Integer ctlType) {
        this.ctlType = ctlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_state.device_type
     *
     * @return the value of t_device_state.device_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_state.device_type
     *
     * @param deviceType the value for t_device_state.device_type
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setDeviceType(Integer deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_state.value
     *
     * @return the value of t_device_state.value
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_state.value
     *
     * @param value the value for t_device_state.value
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setValue(Integer value) {
        this.value = value;
    }
}