package com.hotel.model;

public class Hotel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.name
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.region_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hotel.note
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.id
     *
     * @return the value of t_hotel.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.id
     *
     * @param id the value for t_hotel.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.name
     *
     * @return the value of t_hotel.name
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.name
     *
     * @param name the value for t_hotel.name
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.region_id
     *
     * @return the value of t_hotel.region_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.region_id
     *
     * @param regionId the value for t_hotel.region_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hotel.note
     *
     * @return the value of t_hotel.note
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hotel.note
     *
     * @param note the value for t_hotel.note
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setNote(String note) {
        this.note = note;
    }
}