package com.hotel.model;

public class Rcu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rcu.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rcu.room_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private Integer roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_rcu.rcu_no
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    private String rcuNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rcu.id
     *
     * @return the value of t_rcu.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rcu.id
     *
     * @param id the value for t_rcu.id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rcu.room_id
     *
     * @return the value of t_rcu.room_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public Integer getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rcu.room_id
     *
     * @param roomId the value for t_rcu.room_id
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_rcu.rcu_no
     *
     * @return the value of t_rcu.rcu_no
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public String getRcuNo() {
        return rcuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_rcu.rcu_no
     *
     * @param rcuNo the value for t_rcu.rcu_no
     *
     * @mbggenerated Mon Aug 24 23:10:28 CST 2015
     */
    public void setRcuNo(String rcuNo) {
        this.rcuNo = rcuNo;
    }
}